version: '3.8'

# Using for convenient postgresql database start-up
services:
  postgres_database:
    container_name: postgres_database_container
    image: postgres:alpine3.18
    ports:
      - "5432:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./data/database/volume:/app/database/volume