version: '3.8'

services:
  postgres_database:
    container_name: postgres
    image: postgres:alpine3.18
    ports:
      - "5432:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./data/database/volume:/app/database/volume

  admin_panel:
    build: admin_panel/.
    container_name: admin_panel

    restart: always
    depends_on:
      - postgres_database
    links:
      - postgres_database
    ports:
      - "5000:${SERVER_PORT}"

  bot:
    build: tg_bot/.
    container_name: tg_bot
    restart: always
    depends_on:
      - postgres_database
    links:
      - postgres_database